spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1


spring.cloud.gateway.routes[1].id=merchant-service
spring.cloud.gateway.routes[1].uri=lb://MERCHANT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/merchant/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/